config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root to: "contacts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:firstName, :lastName, :photo_url, :mobile, :work)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="column is-half">
      <div class="field">
          <%= form.label :firstName, class: "label" %>
          <%= form.text_field :firstName, class: "input" %>
      </div>
    </div>

    <div class="column is-half">
      <div class="field">
        <%= form.label :lastName, class: "label" %>
        <%= form.text_field :lastName, class: "input" %>
      </div>
    </div>

    <div class="column is-half">
      <div class="field">
        <%= form.label :photo_url, class: "label" %>
        <%= form.text_field :photo_url, class: "input" %>
      </div>
    </div>

    <div class="column is-half">
      <div class="field">
        <%= form.label :mobile, class: "label" %>
        <%= form.text_field :mobile, class: "input" %>
      </div>
    </div>

    <div class="column is-half">
      <div class="field">
        <%= form.label :work, class: "label" %>
        <%= form.text_field :work, class: "input" %>
      </div>
    </div>

    <div class="column is-half">
      <div class="actions">
        <%= form.submit class: "button is-normal" %>
      </div>
    </div>

<% end %>

app/views/contacts/edit.html.erb
<div class="colums">
  <div class="column is-half">
    <h1 class="is-size-3">Edit contact</h1>
  </div>

  <%= render 'form', contact: @contact %>

  <div class="column is-half">
    <%= link_to 'Show', @contact, class: "button is-small is-link is-light" %> |
    <%= link_to 'Back', contacts_path, class: "button is-small is-link is-light" %>
  </div>
</div>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="columns is-multiline ">
    <% @contacts.each do |contact| %>
      <div class="column is-one-third">
          <div class="card">
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= image_tag "#{contact.photo_url}" %>
                  </figure>
                </div>
                <div class="media-content">
                  <p class="title is-4"><%= contact.firstName %> <%= contact.lastName %></p>
                  <p class="subtitle is-6">M: <%= contact.mobile %> | T: <%= contact.work %></p>
                  <p class="subtitle is-6"><%= link_to 'Show', contact, class: "button is-small is-link is-light" %> | <%= link_to 'Edit', edit_contact_path(contact), class: "button is-small is-link is-light" %> | <%= link_to 'Destroy', contact, class: "button is-small is-danger is-light" ,method: :delete, data: { confirm: 'Are you sure?' } %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
</div>

app/views/contacts/new.html.erb
<div class="colums">
  <div class="column is-half">
    <h1 class="is-size-3">Add new contact</h1>
  </div>
  <%= render 'form', contact: @contact %>

  <div class="column is-half">
    <%= link_to 'Back', contacts_path, class: "button is-small is-link is-light" %>
  </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="columns is-centered">
  <div class="column is-three-quarters">
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-96x96">
                <%= image_tag "#{@contact.photo_url}" %>
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= @contact.firstName %> <%= @contact.lastName %></p>
              <p class="subtitle is-6">M: <%= @contact.mobile %> | T: <%= @contact.work %></p>
              <p class="subtitle is-6"><%= link_to 'Edit', edit_contact_path(@contact), class: "button is-small is-link is-light" %> |
              <%= link_to 'Back', contacts_path, class: "button is-small is-link is-light" %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Home', root_path, class: "navbar-item" %>
    </div>

    <div class="navbar-end">
      <%= link_to 'New Contact', new_contact_path, class: "navbar-item" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phonebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>